[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000
via_ir = true
solc = "0.8.26"
verbosity = 2
ffi = true
fs_permissions = [
  { access = "read-write", path = ".forge-snapshots"},
  { access = "read", path = "script/" }
]

remappings = [
  "forge-std=lib/forge-std/src",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
  "solady=lib/solady/src",
  "permit2=lib/permit2",
  "v4-periphery=lib/v4-periphery"
]

additional_compiler_profiles = [
  { name = "test", via_ir = false }
]

compilation_restrictions = [
  { paths = "src/AuctionFactory.sol", via_ir = false, optimizer = false, optimzer_runs = 0 },
  { paths = "test/**", via_ir = false }
]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
fail_on_revert = true
runs = 100
depth = 200

[profile.pr.fuzz]
runs = 10000

[profile.ci.fuzz]
runs = 100000

[profile.debug]
via_ir = false
optimizer_runs = 200
fuzz.runs = 100

[fmt]
line_length = 120
tab_width = 4
quote_style = "single"
sort_imports = true
number_underscore = "thousands"
