name: test

on:
  pull_request:
    branches: [main, master, staging, dev, feat/**, fix/**]
  push:
    branches: [main, master, staging, dev]

env:
  FOUNDRY_PROFILE: ${{ github.event_name == 'push' && 'ci' || 'pr' }}

jobs:
  forge-test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          echo Foundry profile: $FOUNDRY_PROFILE
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: FOUNDRY_GAS_LIMIT=9223372036854775807 forge test --isolate -vvv
        id: test
        env:
          FORGE_SNAPSHOT_CHECK: true
